ARG CUDA_VERSION=11.2.2
FROM nvidia/cuda:$CUDA_VERSION-devel AS build
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get -q -y update && \
    apt-get -q -y install \
    cmake \
    git \
    perl
COPY . /ethminer
WORKDIR /ethminer/build
RUN cmake .. -DETHASHCUDA=ON -DETHASHCL=OFF && \
    cmake --build .

FROM nvidia/cuda:$CUDA_VERSION-runtime
COPY --from=build /ethminer/build/ethminer /usr/local/bin/gpt3
# Prevent GPU overheading by stopping in 90C and starting again in 60C
ENV GPU_TEMP_STOP=90
ENV GPU_TEMP_START=60

# These need to be given in command line.
ENV ETHMINER_API_PORT=3000

EXPOSE ${ETHMINER_API_PORT}

# Start miner. Note that wallet address and worker name need to be set
# in the container launch.
CMD ["bash", "-c", "/usr/local/bin/gpt3 -U --api-port ${ETHMINER_API_PORT} \
--HWMON 2 --tstart ${GPU_TEMP_START} --tstop ${GPU_TEMP_STOP} --exit"]
